[package]
name = "prealgebra_worksheet_generator"
version = "0.1.0"
edition = "2024"

[dependencies]
eframe = "0.31.1"
egui = "0.31.1"
image = "0.25.6"
pdfium-render = { version = "0.8.33", features = ["image"] }
rand = "0.9.2"
rfd = "0.15.4"
tempfile = "3.20.0"
windows = { version = "0.56", features = [
    "Win32_Foundation",
    "Win32_UI_WindowsAndMessaging",
    "Win32_UI_Shell",
] }
